### ISSUE TITLE
Question: Can this work on...

### ISSUE THREAD

**Issue by danwalmsley** [kodi-pvr/pvr.filmon#129]
Linux kodi boxes like OSMC (debian based arm64).

I was not able to find out how to install this addon. Would I need to compile it myself?

Many thanks

**Comment by phunkyfish** [comment]
I believe on OSMC the addon is shipped with it. But for support please ask on the OSMC forum.

**Comment by danwalmsley** [comment]
I added a PR to improve the readme, that would have pointed this out to me.

https://github.com/kodi-pvr/pvr.filmon/pull/130

**Comment by samnazarko** [comment]
This is supported and shipped on OSMC.
