### ISSUE TITLE
How to re-install FilmOn PVR after un-installing

### ISSUE THREAD

**Issue by pramster** [kodi-pvr/pvr.filmon#53]
I know this is probably not the right place for this issue, but I am trying to find a way to re-install the FilmOn PVR client, after accidentally un-installing it from Kodi on my Amazon Fire TV, as it no longer appears in the PVR Client list.

I have already downloaded the Jarvis zip file, and tried to install it, but I get an error message, and I can't install.

What is the easiest way for me to re-install the FilmOn PVR client again?

Thanks.

**Comment by Jalle19** [comment]
You'll have to reinstall Kodi. I don't know why a) people uninstall system addons and b) why it's even possible, but at the moment reinstalling is the only solution unless something has changed recently.

**Comment by pramster** [comment]
Thanks Jalle. It sounds like a real pain to do, but I'm going to have to do it.

**Comment by Jalle19** [comment]
You can try the forums to see if someone has another solution. Remember to back up your userdata if you decide to reinstall.
