### ISSUE TITLE
Issues with other PVR Backends

### ISSUE THREAD

**Issue by A-Duck** [kodi-pvr/pvr.filmon#54]
I'm having issues using Filmon PVR with other backends.
I've tried running Filmon alongside IPTV Simple and MythTV (Filmon/IPTV Simple or Filmon/MythTV) whenever I do this Filmon will log in but usually wont load the channels, the few occasions when filmon channels are loaded the EPG data is empty while the other backent will be loaded correctly.
When Filmon is run on its own the channels and EPG are both loaded correctly.

**Comment by ksooo** [comment]
Running multiple pvr addons in parallel is not officially supported. If it works, fine, if not, no support. Sorry that I have to say that but pvr devs currently have very limited resources and as we consider this an edge case we concentrate on other issues.
