### ISSUE TITLE
Filmon API changes possibly causing user login issues with pvr.filmon?

### ISSUE THREAD

**Issue by Mike-KL** [kodi-pvr/pvr.filmon#55]
Ref following kodi pvr.filon thread, looks like Filmon API changes may be causing problems for addon.
(I have added a kodi log and screen grab in the thread)

http://forum.kodi.tv/showthread.php?tid=296713

Drt1989 user adding above thread has also included some additional info in other threads i.e.

http://blog.artesea.co.uk/2016/11/filmon...pdate.html

Hope someone knowledgable can take a look and hopefully provided a fix to this very useful pvr addon.

**Comment by Mike-KL** [comment]
@Ksooo & @hudokkow  I noted that you have contributed most to this pvr addon.

Not sure of best debug settings in kodi in order to provide more information and clues on issue, but have had a go with verbose logging for libcURL enabled http://pastebin.com/jbhHLAMn

**Comment by Mike-KL** [comment]
@mcaptur & @ksooo 

OK, fix provided works on an rpi2 with minor limitations thank you
(i.e. epg data is not currently downloaded/included)

http://forum.kodi.tv/showthread.php?tid=269814&pid=2459416#pid2459416

But note: I have installed Krypton nightly builds on Win10 and macOS Sierra and although filmon favourite channels appear to load correctly they do not playback successfully in either enviroment.

http://forum.kodi.tv/showthread.php?tid=297360&pid=2459446#pid2459446

**Comment by mcaptur** [comment]
epg fixed

**Comment by Mike-KL** [comment]
@mcaptur quickly tried on my rpi2 using millhouse build #1129 which includes fix and yes it appears to commence request for EPG data after loading channels, where in my case the first channel to be EPG searched is UK channel C4 where just seems to be perm stuck searching? (Only performed one test, so far)

http://pastebin.com/EpCKmcG8
http://imgur.com/gjmbRCs

Can I provide any specific de-bug data, or try test again in particuar/another way?

**Comment by mcaptur** [comment]
this used to happen before.. are you using two pver backends? delete epg and tv databases and try again

**Comment by Mike-KL** [comment]
Yes I am currently switching between two pvr backends during tests (enabling only one at a time) but confirm am absloutely not using both at same time. I disabled TVheadend42 before enabling pvr.filmon and thats when it got stuck.  On your advise and disabling both pvrs, stoping kodi via ssh, deleting EPG & TV dbs, then retarting kodi and enabling pvr.filmon resolved issue and EPG loaded fine. Thanks

http://imgur.com/qnAvaBF

**Comment by Mike-KL** [comment]
@mcaptur 

Kodi Crashlog at 09:30 (may not be related to pvr.filmon and EPG etc) I was at work, family wanted to watch french catchup (They noticed a crash when trying to move through GUI to addon) https://gist.github.com/Mike-KL/d1f6e2920990dfcb3722e473e1c24354

Arrived home and noticed EPG stalled again on EPG for UK C4 like i mentioned in earlier post
kodi.log https://gist.github.com/Mike-KL/65db545ecac2dce2a9ab8ee00733faf1

Then deliberately restarted kodi and attempted to disable pvr.Filmon after pause occured on EPG for UK C4 and kodi currently unresponsive from point of selecting pvr.filmon disable option in addon information option.

kodi.log https://gist.github.com/Mike-KL/eef209b9139a89c744df28c8976a0594

(Note: Also noticed this last point this morning during intail test before stoping kodi to delete TV and EPG DB's and start with new cleanly created db's)

Hope information is helpful

**Comment by mcaptur** [comment]
The first crash isn't related.. the second crash used to happen to me before these api changes also remember whenever you change between pvr addons delete tv and epg databases 
also set epg not to be stored to db

**Comment by Mike-KL** [comment]
Thanks for tips, so we generally understand everything now working as before in relation to recent filmon API changes.
